databases:
  - name: filiya-db
    plan: free
    databaseName: filiya_db
    user: filiya_user

services:
  - type: web
    name: filiya-backend
    runtime: go
    plan: free
    buildCommand: go build -tags netgo -ldflags '-s -w' -o app ./cmd
    startCommand: ./app
    healthCheckPath: /api
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: filiya-db
          property: connectionString
      - key: GO_VERSION
        value: 1.24.4
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://filiya-frontend.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://filiya-frontend.onrender.com
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URL
        sync: false
